apiVersion: v1
kind: Service
metadata:
  labels:
    app: utkarsh
  name: utkarsh
  namespace: utkarsh
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: utkarsh
  type: LoadBalancer
